import { Inter } from "next/font/google";
import "./globals.css";
import Script from "next/script";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
       <Script
        src={`https://maps.googleapis.com/maps/api/js?key=${process.env.NEXT_PUBLIC_API_KEY}&callback=initMap&libraries=places,drawing&v=weekly&v=weekly`}
        defer></Script>
      <Script src="https://polyfill.io/v3/polyfill.min.js?features=default"></Script>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
